WebSiteBanHang/Controllers/QuanLySanPhamController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSiteBanHang.Models;

namespace WebSiteBanHang.Controllers
{
    public class QuanLySanPhamController : Controller
    {
        //
        // GET: /QuanLySanPham/
        QuanLyBanHangEntities db = new QuanLyBanHangEntities();
        public ActionResult Index()
        {

            return View(db.SanPhams.Where(n => n.DaXoa == false).OrderByDescending(nameof=>nameof.MaSP));
        }
        [HttpGet]
        public ActionResult TaoMoi()
        {
            //load dropdownlist nhà cung cấp
            ViewBag.MaNCC =new SelectList(db.NhaCungCaps.OrderBy(n => n.TenNCC), "MaNCC", "TenNCC");
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSanPhams.OrderBy(n => n.MaLoaiSP), "MaLoaiSP", "TenLoai");
            ViewBag.MaNSX = new SelectList(db.NhaSanXuats.OrderBy(n => n.MaNSX), "MaNSX", "TenNSX");
            return View();
        }
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult TaoMoi(SanPham sp,HttpPostedFileBase HinhAnh)
        {
            ViewBag.MaNCC = new SelectList(db.NhaCungCaps.OrderBy(n => n.TenNCC), "MaNCC", "TenNCC");
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSanPhams.OrderBy(n => n.MaLoaiSP), "MaLoaiSP", "TenLoai");
            ViewBag.MaNSX = new SelectList(db.NhaSanXuats.OrderBy(n => n.MaNSX), "MaNSX", "TenNSX");
            if (HinhAnh.ContentLength > 0)
            {
                var fileName = Path.GetFileName(HinhAnh.FileName);
                var path = Path.Combine(Server.MapPath("~/Content/HinhAnhSP"), fileName);
                if (System.IO.File.Exists(path))
                {
                    ViewBag.upload = "Hình đã tồn tại";
                    return View();
                }
                else
                {
                    HinhAnh.SaveAs(path);
                    sp.HinhAnh = fileName;
                  
                }
               


            }
            db.SanPhams.Add(sp);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WebSiteBanHang/Views/QuanLySanPham/Index.cshtml
@using WebSiteBanHang.Models;
@model IEnumerable<SanPham>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
    //Khởi tạo control WebGrid
    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 5);
}

@*Thể hiện dữ liệu thông qua control webGrid*@
@grid.GetHtml(
    tableStyle: "divTable",
    headerStyle: "gridHead",
    footerStyle: "gridFooter",
    rowStyle: "gridRow",
    alternatingRowStyle: "gridAltRow",
    columns: grid.Columns(
    grid.Column("MaSP", "Mã sản phẩm"),
    grid.Column("TenSP", "Tên SP"),
   
    grid.Column("HinhAnh", "Hình ảnh", format: p => @Html.Raw("<img width=\"150\" height=\"50\"src=\"../Content/HinhAnhSP/" + p.HinhAnh + "\">"))
    ))


@*Css cho từng Style của table*@
<style>
    .divTable {
        border: 1px solid #999999;
    }

    .gridHead {
        background-color: Green;
    }

        .gridHead > th > a {
            color: #fff;
        }

    .gridFooter {
        font-weight: bold;
    }

    .gridRow {
        color: #fff;
        background-color: blueviolet;
    }

    .gridAltRow {
        color: #fff;
        background-color: darkorange;
    }
</style>

WebSiteBanHang/Views/QuanLySanPham/TaoMoi.cshtml
@model WebSiteBanHang.Models.SanPham

@{
    ViewBag.Title = "TaoMoi";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>Tạo Mới Sản Phẩm</h2>
<script src="~/Content/tinymce/js/tinymce/tinymce.min.js"></script>
<script type="text/javascript">
tinymce.init({
    selector: "textarea",
    plugins: [
        "advlist autolink lists link image charmap print preview anchor",
        "searchreplace visualblocks code fullscreen",
        "insertdatetime media table contextmenu paste"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
});
</script>


@using (Html.BeginForm("TaoMoi", "QuanLySanPham", FormMethod.Post, new {
@enctype="multipart/form-data"}))

{
    
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true)
     

        <div class="form-group">
            @Html.LabelFor(model => model.TenSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSP)
                @Html.ValidationMessageFor(model => model.TenSP)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DonGia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DonGia)
                @Html.ValidationMessageFor(model => model.DonGia)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayCapNhap, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               <input name="NgayCapNhap" type="date" />
                @Html.ValidationMessageFor(model => model.NgayCapNhap)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CauHinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CauHinh)
                @Html.ValidationMessageFor(model => model.CauHinh)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               <textarea name="MoTa"></textarea>
                @Html.ValidationMessageFor(model => model.MoTa)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhAnh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
              <input name="HinhAnh" type="file"/>
              <span style="color:red;" >@ViewBag.upload</span>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuongTon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuongTon)
                @Html.ValidationMessageFor(model => model.SoLuongTon)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LuotXem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LuotXem)
                @Html.ValidationMessageFor(model => model.LuotXem)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LuotBinhChon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LuotBinhChon)
                @Html.ValidationMessageFor(model => model.LuotBinhChon)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LuotBinhLuan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LuotBinhLuan)
                @Html.ValidationMessageFor(model => model.LuotBinhLuan)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLanMua, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLanMua)
                @Html.ValidationMessageFor(model => model.SoLanMua)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Moi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Moi)
                @Html.ValidationMessageFor(model => model.Moi)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaNCC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.DropDownList("MaNCC", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaNCC)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaNSX, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.DropDownList("MaNSX", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaNSX)
               
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaLoaiSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.DropDownList("MaLoaiSP", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaLoaiSP)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DaXoa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DaXoa)
                @Html.ValidationMessageFor(model => model.DaXoa)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhAnh1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HinhAnh1)
                @Html.ValidationMessageFor(model => model.HinhAnh1)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhAnh2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HinhAnh2)
                @Html.ValidationMessageFor(model => model.HinhAnh2)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhAnh3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HinhAnh3)
                @Html.ValidationMessageFor(model => model.HinhAnh3)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhAnh4, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HinhAnh4)
                @Html.ValidationMessageFor(model => model.HinhAnh4)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>